const OBX_ID = 1;
const VALUE_TYPE = 2;
const OBSERVATION_VALUE = 5;
const OBSERVATION_IDENTIFIER = 3;
const OBSERVATION_RESULT_STATUS = 11;

// subfields
_OBSERVATION_IDENTIFIER = 1;

const RESULTS = {
  ID: "1",
  IDENTIFIER_ID: "OBX-REPORT",
  VALUE_TYPE: {
    ENCAPSULATED_DATA: "ED",
    STRING_DATA: "ST",
  },
  STATUS: {
    PARTIAL_RESULT: "S",
    RESULT_ENTER_NOT_VERIFIED: "R",
  },
};

module.exports = {
  OBX_ID,
  RESULTS,
  VALUE_TYPE,
  OBSERVATION_VALUE,
  OBSERVATION_IDENTIFIER,
  _OBSERVATION_IDENTIFIER,
  OBSERVATION_RESULT_STATUS,
};
