const OBSERVATION_VALUE = 5;
const OBSERVATION_IDENTIFIER = 3;
const OBSERVATION_RESULT_STATUS = 11;

// subfields
_OBSERVATION_IDENTIFIER = 1;

module.exports = {
  OBSERVATION_VALUE,
  OBSERVATION_IDENTIFIER,
  _OBSERVATION_IDENTIFIER,
  OBSERVATION_RESULT_STATUS,
};
