const { getDateTime } = require("./getCurrentDateTime");

const generateRandomNumber = (min, max) => {
  const randomNumber = Math.floor(Math.random() * (max - min + 1)) + min;
  return randomNumber;
};

//Filename: CASE_(autogenerated Number 1-1000)_MessageType_DATETIME.txt
const generateFileName = (message_type) => {
  const randomNumber = generateRandomNumber(1, 1000);
  const dateTime = getDateTime();

  const fileName = `CASE_${randomNumber}_${message_type}_${dateTime}.txt`;
  return fileName;
};

module.exports = { generateFileName };
