module.exports = {
  FULL_NAME: "fullName",
  DO_BIRTH: "doBirth",
  PHONE_NUMBER: "phoneNumber",
  EMAIL: "email",
  PATIENT_ID: "patientId",
  MRN_NUMBER: "mrnNumber",
  STREET: "street",
  CITY: "city",
  STATE: "state",
  MARITAL_STATUS: "maritalStatus",
  SEX: "sex",
  SSN_NUMBER: "ssnNumber",
  SENDER_APPLICATION: "senderApplication",
  SENDER_FACILITY: "senderFacility",
  SENDER_DATE: "senderDate",
  MESSAGE_TYPE: "messageType",
};
