const {
  VERSION_ID,
  _VERSION_ID,
  SENDING_APP,
  _EVENT_TIME,
  MESSAGE_TYPE,
  RECEIVING_APP,
  PROCESSING_ID,
  _MESSAGE_CODE,
  _TRIGGER_EVENT,
  _PROCESSING_ID,
  FIELD_SEPARATOR,
  MSH_MODEL_NAME,
  MESSAGE_DATETIME,
  _SA_NAMESPACE_ID,
  _RA_NAMESPACE_ID,
  MESSAGE_CONTROL_ID,
  _MESSAGE_STRUCTURE,
  ENCODING_CHARACTERS,
} = require("../constants/message");
const { MSH_MODEL } = require("../models/msh.model");

const MSH_SEGMENT = {
  [MSH_MODEL_NAME]: MSH_MODEL.NAME,
  [FIELD_SEPARATOR]: MSH_MODEL.FIELD_SEPARATOR,
  [ENCODING_CHARACTERS]: MSH_MODEL.ENCODING_CHARACTERS,
  [SENDING_APP]: {
    [_SA_NAMESPACE_ID]: MSH_MODEL.SENDING_APP.NAMESPACE_ID,
  },
  [RECEIVING_APP]: {
    [_RA_NAMESPACE_ID]: MSH_MODEL.RECEIVING_APP.NAMESPACE_ID,
  },
  [MESSAGE_DATETIME]: {
    [_EVENT_TIME]: MSH_MODEL.MESSAGE_DATETIME.EVENT_TIME,
  },
  [MESSAGE_TYPE]: {
    [_MESSAGE_CODE]: MSH_MODEL.MESSAGE_TYPE.MESSAGE_CODE,
    [_TRIGGER_EVENT]: MSH_MODEL.MESSAGE_TYPE.TRIGGER_EVENT,
    [_MESSAGE_STRUCTURE]: MSH_MODEL.MESSAGE_TYPE.MESSAGE_STRUCTURE,
  },
  [MESSAGE_CONTROL_ID]: MSH_MODEL.MESSAGE_CONTROL_ID,
  [PROCESSING_ID]: {
    [_PROCESSING_ID]: MSH_MODEL.PROCESSING_ID.ID,
  },
  [VERSION_ID]: {
    [_VERSION_ID]: MSH_MODEL.VERSION_ID.ID,
  },
};

module.exports = { MSH_SEGMENT };
