const {
  MESSAGE,
  VERSION_ID,
  _VERSION_ID,
  SENDING_APP,
  _EVENT_TIME,
  MESSAGE_TYPE,
  RECEIVING_APP,
  PROCESSING_ID,
  _MESSAGE_CODE,
  _TRIGGER_EVENT,
  _PROCESSING_ID,
  MSH_MODEL_NAME,
  FIELD_SEPARATOR,
  MESSAGE_DATETIME,
  _SA_NAMESPACE_ID,
  _RA_NAMESPACE_ID,
  MESSAGE_CONTROL_ID,
  _MESSAGE_STRUCTURE,
  ENCODING_CHARACTERS,
} = require("../constants/message");
const { SEGMENT } = require("../constants/segment");

const MSH_SEGMENT = (MESSAGE_CODE, TRIGGER_EVENT, MESSAGE_STRUCTURE)=>{
  const mshSegment = {
    [MSH_MODEL_NAME]: SEGMENT.MSH,
    [FIELD_SEPARATOR]: MESSAGE.FIELD_SEPARATOR,
    [ENCODING_CHARACTERS]: MESSAGE.ENCODING_CHARACTERS,
    [SENDING_APP]: {
      [_SA_NAMESPACE_ID]: MESSAGE.SENDING_APP,
    },
    [RECEIVING_APP]: {
      [_RA_NAMESPACE_ID]: MESSAGE.RECEIVING_APP,
    },
    [MESSAGE_DATETIME]: {
      [_EVENT_TIME]: MESSAGE.DATETIME,
    },
    [MESSAGE_TYPE]: {
      [_MESSAGE_CODE]: MESSAGE_CODE,
      [_TRIGGER_EVENT]: TRIGGER_EVENT,
      [_MESSAGE_STRUCTURE]: MESSAGE_STRUCTURE,
    },
    [MESSAGE_CONTROL_ID]: MESSAGE.MESSAGE_CONTROL_ID,
    [PROCESSING_ID]: {
      [_PROCESSING_ID]: MESSAGE.PROCESSING_ID.TRAINING,
    },
    [VERSION_ID]: {
      [_VERSION_ID]: MESSAGE.VERSION_ID,
    },
  };

  return mshSegment;
}



module.exports = { MSH_SEGMENT };
