const {
  VALUE_TYPE,
  OBSERVATION_VALUE,
  OBSERVATION_IDENTIFIER,
  _OBSERVATION_IDENTIFIER,
  OBSERVATION_RESULT_STATUS,
} = require("../constants/observationResult");
const { OBX_MODEL } = require("../models/obx.model");

const OBX_SEGMENT = {
  [OBSERVATION_IDENTIFIER]: {
    [_OBSERVATION_IDENTIFIER]: OBX_MODEL.OBSERVATION_IDENTIFIER.ID,
  },
  [VALUE_TYPE]: OBX_MODEL.VALUE_TYPE,
  [OBSERVATION_VALUE]: OBX_MODEL.OBSERVATION_VALUE,
  [OBSERVATION_RESULT_STATUS]: OBX_MODEL.OBSERVATION_RESULT_STATUS,
};

module.exports = { OBX_SEGMENT };
