const {
  DOB,
  SEX,
  _DOB,
  _CITY,
  ADDRESS,
  _COUNTRY,
  PATIENT_ID,
  PHONENUMBER,
  _FIRST_NAME,
  PATIENT_NAME,
  _FAMILY_NAME,
  _PID_LIST_ID,
  _COUNTRY_CODE,
  _LOCAL_NUMBER,
  MARITAL_STATUS,
  _NAME_TYPE_CODE,
  _MARITAL_STATUS,
  _PID_LIST_TYPE_CODE,
  PATIENT_SEGMENT_NAME,
  PATIENT_IDENTIFIER_LIST,
} = require("../constants/patientIdentification");
const { PID_MODEL } = require("../models/pid.model");

const PID_SEGMENT = {
  [PATIENT_SEGMENT_NAME]: PID_MODEL.NAME,
  [PATIENT_ID]: PID_MODEL.PATIENT_ID,
  [PATIENT_NAME]: [
    {
      [_FAMILY_NAME]: PID_MODEL.PATIENT_NAME.FAMILY_NAME,
      [_FIRST_NAME]: PID_MODEL.PATIENT_NAME.FIRST_NAME,
      [_NAME_TYPE_CODE]: PID_MODEL.PATIENT_NAME.TYPE_CODE,
    },
  ],
  [PATIENT_IDENTIFIER_LIST]: [
    {
      [_PID_LIST_ID]: PID_MODEL.PATIENT_IDENTIFIER_LIST.ID,
      [_PID_LIST_TYPE_CODE]: PID_MODEL.PATIENT_IDENTIFIER_LIST.ID_TYPE_CODE,
    },
  ],
  [DOB]: {
    [_DOB]: PID_MODEL.DATE_OF_BIRTH.DATE_TIME,
  },
  [PHONENUMBER]: [
    {
      [_COUNTRY_CODE]: PID_MODEL.PHONENUMBER.COUNTRY_CODE,
      [_LOCAL_NUMBER]: PID_MODEL.PHONENUMBER.LOCAL_NUMBER,
    },
  ],
  [MARITAL_STATUS]: {
    [_MARITAL_STATUS]: PID_MODEL.MARITAL_STATUS.IDENTIFIER,
  },
  [SEX]: PID_MODEL.SEX,
  [ADDRESS]: [
    {
      [_CITY]: PID_MODEL.ADDRESS.CITY,
      [_COUNTRY]: PID_MODEL.ADDRESS.COUNTRY,
    },
  ],
};

module.exports = { PID_SEGMENT };
