const {
  ROOM,
  BED_STATUS,
  PATIENT_CLASS,
  POINT_OF_CARE,
  HOSPITAL_SERVICE,
  ASSIGNED_PATIENT_LOCATION,
} = require("../constants/patientVisit");
const { PV1_MODEL } = require("../models/pv1.model");

const PV1_SEGMENT = {
  [PATIENT_CLASS]: PV1_MODEL.PATIENT_CLASS,
  [ASSIGNED_PATIENT_LOCATION]: {
    [POINT_OF_CARE]: PV1_MODEL.ASSIGNED_PATIENT_LOCATION.POINT_OF_CARE,
    [ROOM]: PV1_MODEL.ASSIGNED_PATIENT_LOCATION.ROOM,
  },
  [BED_STATUS]: PV1_MODEL.BED_STATUS,
  [HOSPITAL_SERVICE]: PV1_MODEL.HOSPITAL_SERVICE,
};

module.exports = { PV1_SEGMENT };
